version: '3'
services:
    scraper:
        build: ./scraper
        volumes:
          - ./scraper:/project
        restart: unless-stopped
        working_dir: /project
        command: tail -f /dev/null
